version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment: [ALLOW_ANONYMOUS_LOGIN=yes]

  kafka:
    image: bitnami/kafka:latest
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  mongodb:
    image: mongo:latest
    ports: ["27017:27017"]

  productor:
    build: ./productor
    ports: ["8000:8000"]
    depends_on: [kafka]

  consumidor:
    build: ./consumidor
    depends_on: [kafka, mongodb]